[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
clojure-reader = { path = ".." }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "read-string"
harness = false
