[package]
name = "benchmarks"
version = "0.1.0"
edition = "2024"

[dependencies]
clojure-reader = { path = "..", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"
serde = { version = "1.0", features = ["derive"] }

[[bench]]
name = "bench"
harness = false
