name: Code Coverage

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run no-default-features tests with code coverage
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: --no-report --no-default-features --features std --no-fail-fast
      - name: Run default tests with code coverage
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: --no-report --all-features --no-fail-fast
      - name: Run examples with code coverage
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: --no-report --examples
      - name: Generate Report
        uses: actions-rs/cargo@v1
        with:
          command: llvm-cov
          args: report --lcov --output-path lcov.info
      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: lcov.info
